openapi: "3.0.3"
info:
  version: v1
  title: Sample Controller Service
  description: This is an open API specification document for smart-contract-service related operations.
  contact:
    name: Abdul Mueed Shahbaz
    email: abdulmueedshahbaz@gmail.com
  license:
    name: OrderLab
    url: https://example.com
servers:
  - url: 'http://localhost:8040'
    description: Development and Testing Server
  - url: 'http://localhost:8080'
    description: Test automation server
  - url: 'http://localhost:8090'
    description: Acceptance server

tags:
  - name: Sample Controller
    description: Sample Controller

paths:
  /api/v1/sample:
    post:
      tags:
        - Sample
      summary: Create sample
      operationId: createSample
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSampleRequest'
      responses:
        '200':
          description: Response indicates successful creation of the record.
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/MessageInfo'
    get:
      tags:
        - Sample
      summary: Get sample
      operationId: getSample
      responses:
        '200':
          description: Response contains the smart contracts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SampleResponse'

components:
  parameters:
    PageOffset:
      name: pageOffset
      in: query
      schema:
        $ref: "#/components/schemas/PageOffset"

    PageNumber:
      name: pageNumber
      in: query
      schema:
        $ref: "#/components/schemas/PageNumber"

    PageSize:
      name: pageSize
      in: query
      schema:
        $ref: "#/components/schemas/PageSize"

    SortDirection:
      name: sortDirection
      required: false
      in: query
      schema:
        $ref: "#/components/schemas/SortDirection"

    SortBy:
      name: sortBy
      required: false
      in: query
      schema:
        $ref: "#/components/schemas/SortBy"

    SortByUpdatedOn:
      name: sortBy
      required: false
      in: query
      schema:
        $ref: "#/components/schemas/SortByUpdatedOn"

  schemas:
    MessageInfo:
      type: object
      properties:
        messageCode:
          type: string
        messageDescription:
          type: string
        displayableName:
          type: string
        id:
          type: integer
          format: int64
        displayableId:
          type: string

    PageOffset:
      type: integer
      minimum: 0
      default: 0
      example: 0

    PageNumber:
      type: integer
      minimum: 0
      default: 0
      example: 0

    PageSize:
      type: integer
      minimum: 0
      default: 10
      example: 0

    SortDirection:
      type: string
      default: ASC
      enum:
        - ASC
        - DESC

    SortBy:
      type: string
      default: createdOn
      enum:
        - createdOn

    SortByUpdatedOn:
      type: string
      default: updatedOn
      enum:
        - updatedOn

    SampleResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        version:
          type: string
        creatorAddress:
          type: string
        createdOn:
          type: string
        updatedAt:
          type: string
        description:
          type: string
        isActive:
          type: boolean
        participants:
          type: array
          items:
            $ref: "#/components/schemas/ContractParticipantResponse"

    ContractParticipantResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        address:
          type: string
        role:
          type: string
        joinedAt:
          type: string

    CreateSampleRequest:
      type: object
      required: # Required fields, similar to @NotNull
        - creatorAddress
        - description
      properties:
        creatorAddress:
          type: string
          minLength: 1                  # Ensures it’s not blank, similar to @NotBlank
          description: "Creator Address required"
        description:
          type: string
          minLength: 1                  # Ensures it’s not blank, similar to @NotBlank
          description: "Brief description of the contract. Description required"
        participants:
          type: array
          items:
            $ref: "#/components/schemas/ContractParticipantRequest"
        isActive:
          type: boolean
          description: "Whether the contract is active"
          default: true

    ContractParticipantRequest:
      type: object
      required:
        - address
        - role
      properties:
        id:
          type: integer
          format: int64
        address:
          type: string
          minLength: 1
        role:
          type: string
          minLength: 1